<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help()
 */
function facebook_buttons_help($route_name, RouteMatchInterface $route_match) {
  /*switch($route_name) {
    case 'fblikebutton.settings':
      $page_url = Url::fromRoute('block.admin_display');
      $output = '<p>Configure the dynamic Like button. This Like button will like the URL you\'re visiting. ';
      $output .= 'You can set the content types on which the button displays, choose to display it in the ';
      $output .= 'content block or in the links area.</p>';
      $output .= '<p style="font-weight:bold;">You can also configure Static Like Button Blocks in the ' . \Drupal::l('Block Layout page', $page_url) .'</p>';

      return t($output);
  }*/
}

/**
 * Implements hook_theme().
 */
function facebook_buttons_theme() {
  return array(
    'like-button' => array(
      'variables' => _facebook_conf(),
      'template' => 'like-button',
    ),
  );
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function facebook_buttons_node_view(array &$build, EntityInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  $user = $account = \Drupal::currentUser();
  $config = \Drupal::config('facebook_buttons.settings');
  $types = $config->get('like.node_types');
  $teaser_display = $config->get('like.teaser_display');
  $weight = $config->get('like.weight');

  $show = ($types[$node->getType()]) && $user->hasPermission('access facebook buttons');


  if ($show) {
    // Content area
    if (($view_mode == 'teaser' && $teaser_display == true) || ($view_mode == 'full')) {
      $url = _facebook_buttons_get_node_url($node->id());
      $build['facebook_buttons_field'] = array(
        '#theme' => 'like-button',
        '#weight' => $weight,
        '#url' => $url,
      );
    }
  }
}

/**
 * Gets the node url
 *
 * @param $node_id
 *
 * @return \Drupal\Core\GeneratedUrl|string
 */
function _facebook_buttons_get_node_url($node_id) {
  $url_generator = \Drupal::urlGenerator();

  return $url_generator->generateFromRoute('entity.node.canonical', array('node' => $node_id), array('absolute' => TRUE));
}

/**
 * Helper function to generate the configuration array used to generate the like
 * button.
 */
function _facebook_conf() {
  $config = \Drupal::config('facebook_buttons.settings');
  $conf = array(
    'layout' => $config->get('like.layout'),
    'action' => $config->get('like.action'),
    'color_scheme' => $config->get('like.color_scheme'),
    'show_faces' => $config->get('like.show_faces'),
    'font' => $config->get('like.font'),
    'language' => $config->get('like.language'),
    'url' => '',
  );

  return $conf;
}
