<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_theme().
 */
function facebook_buttons_theme() {
  return array(
    'facebook-buttons' => array(
      'variables' => _facebook_conf(),
      'template' => 'facebook-buttons',
    ),
  );
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function facebook_buttons_node_view(array &$build, EntityInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  $user = $account = \Drupal::currentUser();
  $config = \Drupal::config('facebook_buttons.settings');
  $types = $config->get('like.node_types');
  $teaser_display = $config->get('like.teaser_display');
  $weight = $config->get('like.weight');

  $show = ($types[$node->getType()]) && $user->hasPermission('access facebook buttons');


  if ($show) {
    // Content area
    if (($view_mode == 'teaser' && $teaser_display == true) || ($view_mode == 'full')) {
      $url = _facebook_buttons_get_node_url($node->id());
      $build['facebook_buttons_field'] = array(
        '#theme' => 'facebook-buttons',
        '#weight' => $weight,
        '#url' => $url,
        '#buttons' => array('like' => TRUE)
      );
    }
  }
}

/**
 * Gets the node url
 *
 * @param $node_id
 *
 * @return \Drupal\Core\GeneratedUrl|string
 */
function _facebook_buttons_get_node_url($node_id) {
  $url_generator = \Drupal::urlGenerator();

  return $url_generator->generateFromRoute('entity.node.canonical', array('node' => $node_id), array('absolute' => TRUE));
}

/**
 * Helper function to generate the configuration array used to generate the like
 * button.
 */
function _facebook_conf() {
  $config = \Drupal::config('facebook_buttons.settings');
  $conf = array(
    'layout' => $config->get('like.layout'),
    'action' => $config->get('like.action'),
    'width' => $config->get('like.width'),
    'show_faces' => $config->get('like.show_faces'),
    'size' => $config->get('like.size'),
    'language' => $config->get('like.language'),
    'url' => '',
    'buttons' => array()
  );

  return $conf;
}
