<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_theme().
 */
function facebook_widgets_buttons_theme() {
  return array(
    'facebook-buttons' => array(
      'variables' => _facebook_buttons_conf(),
      'template' => 'facebook-buttons',
    ),
  );
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function facebook_widgets_buttons_node_view(array &$build, EntityInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  $user = $account = \Drupal::currentUser();
  $config = \Drupal::config('facebook_widgets_buttons.settings');
  $types = $config->get('like.node_types');
  $teaser_display = $config->get('like.teaser_display');
  $weight = $config->get('like.weight');

  $show = ($types[$node->getType()]) && $user->hasPermission('access facebook buttons');

  if ($show) {
    // Content area
    if (($view_mode == 'teaser' && $teaser_display == true) || ($view_mode == 'full')) {
      $url = _facebook_buttons_get_node_url($node->id());
      $build['facebook_buttons_field'] = array(
        '#theme' => 'facebook-buttons',
        '#buttons' => array('like' => TRUE),
        '#url' => $url,
        '#weight' => $weight,
      );
    }
  }
}

/**
 * Gets the node url
 *
 * @param $node_id
 *
 * @return \Drupal\Core\GeneratedUrl|string
 */
function _facebook_buttons_get_node_url($node_id) {
  $url_generator = \Drupal::urlGenerator();

  return $url_generator->generateFromRoute('entity.node.canonical', array('node' => $node_id), array('absolute' => TRUE));
}

/**
 * Helper function to generate the configuration array used to generate the like
 * button.
 *
 * @return array
 */
function _facebook_buttons_conf() {
  $config = \Drupal::config('facebook_widgets_buttons.settings');
  $conf = array(
    // General variables
    'buttons' => array(),
    'url' => '',
    // Like variables
    'like_url' => '',
    'like_layout' => $config->get('like.layout'),
    'like_action' => $config->get('like.action'),
    'like_width' => $config->get('like.width'),
    'like_show_faces' => $config->get('like.show_faces'),
    'like_size' => $config->get('like.size'),
    'like_share' => $config->get('like.share'),
    // Share variables
    'share_url' => '',
    'share_layout' => '',
    'share_size' => '',
    // Send variables
    'send_url' => '',
    'send_size' => '',
  );

  return $conf;
}
